format_version: 10
pipelines:
  jackstrohm:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-589ea36:
        #git: https://github.com/hoyle1974/jackstrohm.git
        git: http://gitea-http.gitea.svc.cluster.local:3000/gitea-admin/jackstrohm.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - compile:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          compile-jackstrohm:
            elastic_profile_id: hugo
            timeout: 0
            artifacts:
            - build:
                source: output
            tasks:
            - exec:
                arguments:
                  - -c
                  - HUGO_ENV=production hugo 
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - mkdir output
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - mv public output
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - cp ./nginx.conf ./output/nginx.conf
                command: /bin/bash
                run_if: passed
    - package:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          package-jackstrohm:
            elastic_profile_id: buildah
            timeout: 0
            artifacts:
            - build:
                source: build
            tasks:
            - fetch:
                pipeline: jackstrohm
                stage: compile
                job: compile-jackstrohm
                source: output/
            - exec:
                arguments:
                  - -c
                  - find .
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - buildah bud -t jackstrohm:${GO_PIPELINE_LABEL} -f Dockerfile .
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - mkdir build && cd build && buildah push jackstrohm:${GO_PIPELINE_LABEL} oci-archive:./jackstrohm.tar:jackstrohm:${GO_PIPELINE_LABEL}
                command: /bin/bash
                run_if: passed
    - push:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          push-jackstrohm:
            elastic_profile_id: buildah
            timeout: 0
            artifacts:
            tasks:
            - fetch:
                pipeline: jackstrohm
                stage: package
                job: package-jackstrohm
                source: build/
            - exec:
                arguments:
                  - -c
                  - buildah pull oci-archive:./build/jackstrohm.tar 
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - buildah login -u jstrohm -p ${DOCKER_PASSWORD} docker.io
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - buildah push jackstrohm:${GO_PIPELINE_LABEL} docker://jstrohm/jackstrohm:${GO_PIPELINE_LABEL}
                command: /bin/bash
                run_if: passed
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          push-jackstrohm:
            elastic_profile_id: kubectl
            timeout: 0
            artifacts:
            tasks:
            - exec:
                arguments:
                  - -c
                  - kubectl get pod -n default
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - kubectl set image deployment/jackstrohm jackstrohm=jstrohm/jackstrohm:${GO_PIPELINE_LABEL} -n default
                command: /bin/bash
                run_if: passed
